services:
  postgres:
    image: postgres:16-alpine
    container_name: restock-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: restock_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - restock-network

  adminer:
    image: adminer:latest
    container_name: restock-adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - restock-network

volumes:
  postgres-data:
    name: restock-postgres-data

networks:
  restock-network:
    name: restock-network